{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kube-depod.fullname" . }}-metrics
  labels:
    {{- include "kube-depod.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.operator.serverPort }}
      protocol: TCP
      name: metrics
  selector:
    {{- include "kube-depod.selectorLabels" . | nindent 4 }}
{{- end }}
