apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

resources:
  - crd.yaml
  - rbac.yaml
  - deployment.yaml

commonLabels:
  app.kubernetes.io/name: kube-depod
  app.kubernetes.io/version: v0.1.0
  app.kubernetes.io/part-of: kube-depod

commonAnnotations:
  description: "Automated Pod cleanup operator based on Policy CRD"
