name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Run cargo test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      - name: Setup K3s
        uses: nolar/setup-k3d-k3s@v1
        with:
          version: v1.29.1+k3s2

      - name: Run cargo test
        run: cargo test --all-features

      - name: Run integration tests
        run: cargo test --test controller_integration_test -- --ignored
